### ISSUE TITLE
Please make fork private

### ISSUE THREAD

**Issue by teckel12** [thimbleio/NewPing#1]
As per requested on the official NewPing distribution page, if you'd like to fork NewPing, make the fork private to not cause confusion between the official latest release and this fork.

**Comment by davidbrenner** [comment]
Tim, absolutely! I will either rename the fork or delete it. My only intent is to get the library included in the Arduino Library Manager. See: https://github.com/arduino/Arduino/issues/5798

**Comment by teckel12** [comment]
I show the fork as public, and trying to reel back control of this as this is NOT your code or library to take credit for.

**Comment by davidbrenner** [comment]
Hi Tim,

Again, the only intent here was to get your library included in the Arduino Library Manager. It looks like (based on arduino/Arduino#5798), the only thing left for you to do is to create the version tag corresponding to the libraries.properties version number. Once that's done, I'll happily delete this fork. Thanks!

David

**Comment by teckel12** [comment]
It's all sorted out now and NewPing is in the library manager.

**Comment by davidbrenner** [comment]
Awesome, thanks! Deleting this now.
